// Device tests for the Android facade over OrcaSlicer. OrcaSlicer's own suites
// cover the algorithms; these cover what the app adds: loading the bundled
// vendor profiles through PresetBundle and the full slice/export/cancel path.
//
// scripts/engine-test.ps1 pushes the profile bundle and upstream test data to
// ENGINE_DEVICE_TEST_DIR before running this executable.

#include <catch2/catch_test_macros.hpp>

#include <fstream>
#include <iterator>
#include <string>

#include <boost/filesystem.hpp>

#include "orca_engine_adapter.hpp"

namespace orca = orcinus::orca;
namespace fs = boost::filesystem;

namespace {

const std::string device_dir = ENGINE_DEVICE_TEST_DIR;

orca::ProfileSelection k2_plus_profiles()
{
    orca::ProfileSelection profiles;
    profiles.printer = "Creality K2 Plus 0.4 nozzle";
    profiles.filament = "Generic PLA @K2 Plus-all";
    profiles.process = "0.20mm Standard @Creality K2 Plus 0.4 nozzle";
    return profiles;
}

void require_engine()
{
    orca::EngineDirectories directories;
    directories.data_dir = device_dir + "/orca/data";
    directories.resources_dir = device_dir + "/orca/resources";
    directories.temporary_dir = device_dir + "/tmp/orca";
    const orca::EngineInitialization initialization = orca::initialize(directories);
    INFO(initialization.message);
    REQUIRE(initialization.ready);
}

std::string output_path(const std::string& name)
{
    const fs::path path = fs::path(device_dir) / "tmp" / name;
    fs::remove(path);
    return path.string();
}

std::string read_file(const std::string& path)
{
    std::ifstream input(path, std::ios::binary);
    return {std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>()};
}

}  // namespace

TEST_CASE("Bundled K2 Plus profiles slice the calibration cube into Orca G-code", "[Adapter]")
{
    require_engine();
    const std::string output = output_path("cube.gcode");
    int last_percent = -1;

    const orca::SliceResult result = orca::slice(
        "cube",
        {},
        output,
        k2_plus_profiles(),
        [&last_percent](const int percent, const std::string&) { last_percent = percent; }
    );

    INFO(result.message);
    REQUIRE(result.status == orca::SliceStatus::success);
    CHECK(result.layer_count == 100);
    CHECK(result.estimated_print_time_seconds > 0);
    CHECK(result.filament_micrometers > 0);
    CHECK(last_percent >= 80);
    CHECK_FALSE(fs::exists(output + ".part"));

    const std::string gcode = read_file(output);
    CHECK(gcode.find("; generated by OrcaSlicer ") != std::string::npos);
    CHECK(gcode.find("; printer_settings_id = Creality K2 Plus 0.4 nozzle") != std::string::npos);
    CHECK(gcode.find("; filament_settings_id = \"Generic PLA @K2 Plus-all\"") != std::string::npos);
    // z_hop_types comes only from the root fdm_machine_common profile.
    CHECK(gcode.find("; z_hop_types = Normal Lift") != std::string::npos);
}

TEST_CASE("An imported STL is sliced through the same pipeline", "[Adapter]")
{
    require_engine();
    const std::string output = output_path("20mmbox.gcode");

    const orca::SliceResult result = orca::slice(
        "stl",
        device_dir + "/data/test_stl/ASCII/20mmbox-LF.stl",
        output,
        k2_plus_profiles(),
        {}
    );

    INFO(result.message);
    REQUIRE(result.status == orca::SliceStatus::success);
    CHECK(result.layer_count > 0);
    CHECK(fs::file_size(output) > 0);
}

TEST_CASE("Unknown profiles and unreadable models are reported", "[Adapter]")
{
    require_engine();

    orca::ProfileSelection unknown_printer = k2_plus_profiles();
    unknown_printer.printer = "No Such Printer";
    CHECK(orca::slice("unknown", {}, output_path("unknown.gcode"), unknown_printer, {}).status
          == orca::SliceStatus::profile_not_found);

    CHECK(orca::slice("missing", device_dir + "/data/missing.stl", output_path("missing.gcode"), k2_plus_profiles(), {}).status
          == orca::SliceStatus::model_read_failed);
}

TEST_CASE("Cancelling the active job stops slicing without output", "[Adapter]")
{
    require_engine();
    const std::string output = output_path("cancelled.gcode");
    bool other_job_rejected = false;
    bool cancel_accepted = false;

    // Catch2 assertions are not thread-safe; the callback only records results.
    const orca::SliceResult result = orca::slice(
        "cancel-me",
        {},
        output,
        k2_plus_profiles(),
        [&](const int percent, const std::string&) {
            if (percent >= 10 && !cancel_accepted) {
                other_job_rejected = !orca::cancel("other-job");
                cancel_accepted = orca::cancel("cancel-me");
            }
        }
    );

    CHECK(other_job_rejected);
    CHECK(cancel_accepted);
    CHECK(result.status == orca::SliceStatus::cancelled);
    CHECK_FALSE(fs::exists(output));
    CHECK_FALSE(fs::exists(output + ".part"));
}
